# Generated by Django 5.1 on 2024-12-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipped',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Chờ lấy hàng', 'Chờ lấy hàng'), ('Đã hủy', 'Đã hủy'), ('Đang giao', 'Đang giao'), ('Đã giao', 'Đã giao')], default='Chờ lấy hàng', max_length=30),
        ),
    ]
